// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4HNgsMHZcIJgfaZr_D8jWcG3yT6Hd5Nc',
    appId: '1:1071564261251:web:426506289aef6b333598b6',
    messagingSenderId: '1071564261251',
    projectId: 'visitor-app-flutter',
    authDomain: 'visitor-app-flutter.firebaseapp.com',
    storageBucket: 'visitor-app-flutter.appspot.com',
    measurementId: 'G-FXY9VWNP4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgrKmF0jLZ1tbA6Zto3mX-39VfFgYZeU',
    appId: '1:1071564261251:android:438783c1f1c298533598b6',
    messagingSenderId: '1071564261251',
    projectId: 'visitor-app-flutter',
    storageBucket: 'visitor-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2IqZZQXkDrgZpzQ6_XsN3_jHrdHKs5g',
    appId: '1:1071564261251:ios:9999cbcd7e7b82003598b6',
    messagingSenderId: '1071564261251',
    projectId: 'visitor-app-flutter',
    storageBucket: 'visitor-app-flutter.appspot.com',
    iosBundleId: 'com.example.visitorAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN2IqZZQXkDrgZpzQ6_XsN3_jHrdHKs5g',
    appId: '1:1071564261251:ios:9999cbcd7e7b82003598b6',
    messagingSenderId: '1071564261251',
    projectId: 'visitor-app-flutter',
    storageBucket: 'visitor-app-flutter.appspot.com',
    iosBundleId: 'com.example.visitorAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4HNgsMHZcIJgfaZr_D8jWcG3yT6Hd5Nc',
    appId: '1:1071564261251:web:3e952ee07eacf9263598b6',
    messagingSenderId: '1071564261251',
    projectId: 'visitor-app-flutter',
    authDomain: 'visitor-app-flutter.firebaseapp.com',
    storageBucket: 'visitor-app-flutter.appspot.com',
    measurementId: 'G-MKNSLCKVKC',
  );
}
